const Map<String, String> en = {
  "WELCOME TO\nFalcons Point Of Sale": "WELCOME TO\nFalcons Point Of Sale",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "Get Started": "Get Started",
  "Welcome to Falcons Pos": "Welcome to Falcons Pos",
  "Sign In": "Sign In",
  "Username": "Username",
  "Password": "Password",
  "Incorrect username or password": "Incorrect username or password",
  "Login Failed": "Login Failed",
  "Voucher No": "Voucher No",
  "Date": "Date",
  "Time": "Time",
  "Search": "Search",
  "Search for item": "Search for item",
  "Add Item": "Add Item",
  "Hold Items": "Hold Items",
  "Current bill": "Current bill",
  "No of Items": "No of Items",
  "Line Disc": "Line Disc",
  "Total": "Total",
  "Disc": "Disc",
  "Tax": "Tax",
  "Net Total": "Net Total",
  "Item Name": "Item Name",
  "Sold Unit": "Sold Unit",
  "Qty": "Qty",
  "Price": "Price",
  "Net Price": "Net Price",
  "Payment Methods": "Payment Methods",
  "Other Payment Methods": "Other Payment Methods",
  "Cash": "Cash",
  "Action Number": "Action Number",
  "Transactions on the invoice": "Transactions on the invoice",
  "Wait": "Wait",
  "Reservation": "Reservation",
  "Replacing": "Replacing",
  "Return item": "Return item",
  "Delete the last": "Delete the last",
  "Receipts": "Receipts",
  "Payments": "Payments",
  "Open cash": "Open cash",
  "Close cash": "Close cash",
  "End cash": "End cash",
  "Reprint an invoice": "Reprint an invoice",
  "Replace item": "Replace item",
  "Item info": "Item info",
  "Save": "Save",
  "Save invoice": "Save invoice",
  "Customer Payments": "Customer Payments",
  "Logout": "Logout",
  "Balance": "Balance",
  "Exit": "Exit",
  "Clear": "Clear",
  "Visa": "Visa",
  "Master card": "Master card",
  "Remaining": "Remaining",
  "Credit Card": "Credit Card",
  "Delivery charge": "Delivery charge",
  "Line discount":"Line discount",
  "Sub total":"Sub total",
  "Service":"Service",
  "Amount Due":"Amount Due",
  "Total Due":"Total Due",
  "Total received":"Total received",
  "Please select a payment company":"Please select a payment company",
  "Discount":"Discount",
  "Please fill search field":"Please fill search field",
  "Item not found":"Item not found",
  "The account you are logged in with does not have permission":"The account you are logged in with does not have permission",
  "Void Item":"Void Item",
  "Please select the item you want to remove":"Please select the item you want to remove",
  "Please try again":"Please try again",
  "Please select void reason":"Please select void reason",
  "Void Reason":"Void Reason",
  "Void All":"Void All",
  "There must be items":"There must be items",
  "Hold Caption":"Hold Caption",
  "Add":"Add",
  "Cancel":"Cancel",
  "The remainder should be 0":"The remainder should be 0",
  "Print":"Print",
  "Close":"Close",
  "Reprint":"Reprint",
  "takeAway":"Take Away",
  "Order No":"Order No",
  "Invoice No":"Invoice No",
  "User":"User",
  "Phone":"Phone",
  "Pro-Nam":"Pro-Nam",
  "Line Discount":"Line Discount",
  "Delivery Charge":"Delivery Charge",
  "Credit":"Credit",
  "Ok":"Ok",
  "Daily close":"Daily close",
  "Daily Close":"Daily Close",
  "Are you sure?":"Are you sure?",
  "Daily close date":"Daily close date",
  "New daily close date":"New daily close date",
  "Daily closing cannot be done due to order park":"Daily closing cannot be done due to order park",
  "Confirm":"Confirm",
  "Successfully":"Successfully",
  "Reports":"Reports",
  "End Cash":"End Cash",
  "Total Cash":"Total Cash",
  "Total Credit Card":"Total Credit Card",
  "Input":"Input",
  "Actual Value":"Actual Value",
  "Different":"Different",
  "Cash Report":"Cash Report",
  "Sold Qty Report":"Sold Qty Report",
  "Cash In / Out Report":"Cash In / Out Report",
  "cashReport":"Cash Report",
  "soldQtyReport":"Sold Qty Report",
  "cashInOutReport":"Cash In / Out Report",
  "Pay In":"Pay In",
  "Pay out":"Pay out",
  "The value must be greater than zero":"The value must be greater than zero",
  "Please select cash In / Out Type":"Please select cash In / Out Type",
  "History pay In / Out":"History pay In / Out",
  "Pay Out":"Pay Out",
  "Delete pay In / Out":"Delete pay In / Out",
  "Cash In":"Cash In",
  "Cash Out":"Cash Out",
  "Unit":"Unit",
  "Price change is not available for this item":"Price change is not available for this item",
  "Line discount is not available for this item":"Line discount is not available for this item",
  "This field is required":"This field is required",
  "Quantity must be greater than or equal to":"Quantity must be greater than or equal to",
  "Quantity must be less than or equal to":"Quantity must be less than or equal to",
  "The discount cannot be greater than the price of an item":"The discount cannot be greater than the price of an item",
  "Discount cannot be more than %100":"Discount cannot be more than %100",
  "The item price cannot be less than zero":"The item price cannot be less than zero",
  "Please enter valid email":"Please enter valid email",
  "Refund":"Refund",
  "Voucher Number":"Voucher Number",
  "POS No":"POS No",
  "Cashier  No":"Cashier  No",
  "Ret Qty":"Ret Qty",
  "Reprint Invoice":"Reprint Invoice",
  "Show":"Show",
  "Search Item":"Search Item",
  "Item code":"Item code",
  "Item name":"Item name",
  "Item name E":"Item name E",
  "Group":"Group",
  "Mina color":"Mina color",
  "Original No":"Original No",
  "New No":"New No",
  "Sale Price":"Sale Price",
  "Item Photo":"Item Photo",
  "No items accept discount in order":"No items accept discount in order",
  "Please add items":"Please add items",
  "There are no speed items":"There are no speed items",
  "Invoice":"Invoice",
  "Cashier":"Cashier",
  "Customer":"Customer",
  "Item Description":"Item Description",
  "Item Count":"Item Count",
  "Sub Total":"Sub Total",
  "Note":"Note",
  "Thank you & have nice day":"Thank you & have nice day",
  "Last Invoice":"Last Invoice",
  "":"",
};
